/* eslint-disable @typescript-eslint/no-empty-object-type */
// Bindings injected by the vinext runtime. PLUGIN_REGISTRY is generated by
// Wrangler in worker-configuration.d.ts and merges into this interface.
interface RuntimeInjectedEnv {
  ASSETS: Fetcher;
  GITHUB_TOKEN?: string;
  VISIT_DISPLAY_MULTIPLIER?: string;
  VISIT_METRICS?: D1Database;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface Env extends RuntimeInjectedEnv {}

declare namespace Cloudflare {
  interface Env extends RuntimeInjectedEnv {}
}
